/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/office_1.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial012.geometry}
          material={materials["01___Default"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.01, 0.41, 0]} scale={[30, 0.2, 50]}>
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials.Floor_Material}
        />
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials.wall_Material}
        />
        <group position={[0.58, 17.47, -0.89]} scale={[0.24, 0.76, 0.06]}>
          <mesh
            geometry={nodes.Cube007.geometry}
            material={nodes.Cube007.material}
          />
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={nodes.Cube007_1.material}
          />
          <group position={[-0.03, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0015.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0015_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group position={[-0.66, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0016.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0016_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group position={[0.58, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0017.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0017_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[-0.04, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0018.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0018_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0019.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0019_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[-0.65, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0020.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0020_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
        </group>
        <group position={[-0.66, 17.47, -0.89]} scale={[0.24, 0.76, 0.06]}>
          <mesh
            geometry={nodes.Cube017.geometry}
            material={nodes.Cube017.material}
          />
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={nodes.Cube017_1.material}
          />
          <group position={[-0.03, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0021.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0021_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group position={[-0.66, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0022.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0022_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group position={[0.58, -21.99, -0.67]} scale={[0.6, 21.75, 1.37]}>
            <mesh
              geometry={nodes.Object_0023.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0023_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[-0.04, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0024.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0024_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0025.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0025_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[-0.65, -21.99, 0.89]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.6, 21.75, 1.37]}
          >
            <mesh
              geometry={nodes.Object_0026.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0026_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
        </group>
        {/* <mesh
          geometry={nodes.ceiling.geometry}
          material={nodes.ceiling.material}
          position={[0, 47.52, 0]}
        /> */}
        <mesh
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-0.09, 1.02, -0.85]}
          scale={[0.01, 1, 0.15]}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials.Tv_Color}
            position={[2.51, 19.29, 0]}
            scale={[1.11, 0.33, 0.52]}
          />
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials.Tv_Color}
            position={[-2.54, 19.29, 0]}
            scale={[1.11, 0.33, 0.52]}
          />
        </mesh>
        <mesh
          geometry={nodes.Cube015.geometry}
          material={materials.Tv_Color}
          position={[-0.69, 20.31, 0.58]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0, 0.33, 0.13]}
        />
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials.Tv_Color}
          position={[-0.69, 20.31, 0.6]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0, 0.33, 0.13]}
        />
        <group position={[-0.64, 9.36, 0.86]} scale={[0.03, 8.17, 0.06]}>
          {/* <mesh
            geometry={nodes.Cube014.geometry}
            material={materials["Material.003"]}
          /> */}
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["Material.004"]}
          />
          <group position={[4.42, -1.05, 0.06]} scale={[2.89, 1.77, 0.97]}>
            <mesh
              geometry={nodes.Object_0001.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0001_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[2.33, -1.05, -0.61]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[0.97, 1.77, 2.89]}
          >
            <mesh
              geometry={nodes.Object_0002.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0002_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer073.geometry}
            material={materials["01___Default.001"]}
            position={[0.06, 0.74, -0.59]}
            rotation={[-Math.PI, 1.57, -Math.PI]}
            scale={[0.34, 0.61, 1]}
          />
          <mesh
            geometry={nodes.Computer074.geometry}
            material={materials["01___Default.001"]}
            position={[4.35, 0.74, 0.72]}
            rotation={[Math.PI, -0.01, Math.PI]}
            scale={[1, 0.61, 0.34]}
          />
        </group>
        <mesh
          geometry={nodes.left_wall.geometry}
          material={materials.wall_Material}
          position={[1.01, 23.83, 0]}
          rotation={[0, 0, -1.57]}
          scale={[25, 0.01, 1]}
        />
        <mesh
          geometry={nodes.Office_Cubical001.geometry}
          material={nodes.Office_Cubical001.material}
          position={[0.28, 7.44, 0.79]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0004.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0004_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0003.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0003_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1003.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1003_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer003.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer004.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer005.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical002.geometry}
          material={nodes.Office_Cubical002.material}
          position={[0.27, 7.44, 0.97]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0006.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0006_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0005.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0005_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1004.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1004_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer001.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer002.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer006.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical003.geometry}
          material={nodes.Office_Cubical003.material}
          position={[0.81, 7.44, 0.79]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0008.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0008_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0007.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0007_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1005.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1005_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer007.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer008.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer009.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical004.geometry}
          material={nodes.Office_Cubical004.material}
          position={[0.8, 7.44, 0.97]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0010.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0010_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0009.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0009_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1006.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1006_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer010.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer011.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer012.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical005.geometry}
          material={nodes.Office_Cubical005.material}
          position={[0.81, 7.44, 0.56]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0012.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0012_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0011.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0011_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1007.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1007_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer013.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer014.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer015.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical006.geometry}
          material={nodes.Office_Cubical006.material}
          position={[0.8, 7.44, 0.75]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0014.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0014_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0013.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0013_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1008.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1008_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer016.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer017.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer018.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical007.geometry}
          material={nodes.Office_Cubical007.material}
          position={[0.81, 7.44, 0.34]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0030.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0030_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0029.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0029_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1016.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1016_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer019.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer020.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer021.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical008.geometry}
          material={nodes.Office_Cubical008.material}
          position={[0.8, 7.44, 0.52]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0032.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0032_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0031.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0031_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1017.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1017_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer022.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer023.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer024.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical009.geometry}
          material={nodes.Office_Cubical009.material}
          position={[0.81, 7.44, 0.11]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0034.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0034_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0033.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0033_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1018.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1018_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer025.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer026.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer027.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical010.geometry}
          material={nodes.Office_Cubical010.material}
          position={[0.8, 7.44, 0.3]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0036.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0036_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0035.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0035_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1019.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1019_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer028.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer029.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer030.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical011.geometry}
          material={nodes.Office_Cubical011.material}
          position={[0.81, 7.44, -0.11]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0038.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0038_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0037.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0037_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1020.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1020_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer031.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer032.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer033.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical012.geometry}
          material={nodes.Office_Cubical012.material}
          position={[0.8, 7.44, 0.07]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0040.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0040_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0039.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0039_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1021.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1021_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer034.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer035.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer036.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical013.geometry}
          material={nodes.Office_Cubical013.material}
          position={[0.28, 7.44, -0.57]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0052.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0052_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0051.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0051_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1027.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1027_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer037.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer038.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer039.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical014.geometry}
          material={nodes.Office_Cubical014.material}
          position={[0.81, 7.44, -0.34]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0042.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0042_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0041.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0041_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1022.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1022_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer040.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer041.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer042.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical015.geometry}
          material={nodes.Office_Cubical015.material}
          position={[0.8, 7.44, -0.15]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0044.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0044_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0043.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0043_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1023.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1023_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer043.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer044.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer045.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical016.geometry}
          material={nodes.Office_Cubical016.material}
          position={[0.8, 7.44, -0.38]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0048.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0048_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0047.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0047_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1025.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1025_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer046.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer047.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer048.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical017.geometry}
          material={nodes.Office_Cubical017.material}
          position={[0.81, 7.44, -0.57]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0050.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0050_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0049.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0049_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1026.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1026_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer049.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer050.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer051.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical018.geometry}
          material={nodes.Office_Cubical018.material}
          position={[0.27, 7.44, -0.38]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0054.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0054_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0053.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0053_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1028.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1028_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer052.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer053.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer054.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical019.geometry}
          material={nodes.Office_Cubical019.material}
          position={[0.28, 7.44, -0.34]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0056.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0056_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0055.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0055_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1029.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1029_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer055.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer056.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer057.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical020.geometry}
          material={nodes.Office_Cubical020.material}
          position={[0.27, 7.44, -0.15]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0058.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0058_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0057.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0057_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1030.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1030_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer058.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer059.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer060.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical021.geometry}
          material={nodes.Office_Cubical021.material}
          position={[0.28, 7.44, -0.11]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0060.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0060_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0059.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0059_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1031.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1031_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer061.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer062.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer063.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical022.geometry}
          material={nodes.Office_Cubical022.material}
          position={[0.27, 7.44, 0.08]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0062.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0062_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0061.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0061_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1032.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1032_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer064.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer065.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer066.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical023.geometry}
          material={nodes.Office_Cubical023.material}
          position={[0.28, 7.44, 0.12]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0064.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0064_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0063.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0063_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1033.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1033_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer067.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer068.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer069.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Office_Cubical024.geometry}
          material={nodes.Office_Cubical024.material}
          position={[0.27, 7.44, 0.3]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.19, -6.5, -0.02]}
        >
          <group
            position={[-0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_0066.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0066_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.89]}
          >
            <mesh
              geometry={nodes.Object_0065.geometry}
              material={materials["Black.Plastic"]}
            />
            <mesh
              geometry={nodes.Object_0065_1.geometry}
              material={materials["Shiny.Metal"]}
            />
          </group>
          <group
            position={[0.58, -1, -1.7]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.5, -2.22, -2.88]}
          >
            <mesh
              geometry={nodes.Object_1034.geometry}
              material={materials["Shiny.Metal"]}
            />
            <mesh
              geometry={nodes.Object_1034_1.geometry}
              material={materials["Black.Plastic"]}
            />
          </group>
          <mesh
            geometry={nodes.Computer070.geometry}
            material={materials["01___Default.001"]}
            position={[0.58, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer071.geometry}
            material={materials["01___Default.001"]}
            position={[0.02, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
          <mesh
            geometry={nodes.Computer072.geometry}
            material={materials["01___Default.001"]}
            position={[-0.52, 1.5, -0.24]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.17, -0.77, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table002.geometry}
          material={materials["01___Default.001"]}
          position={[-0.2, 4.56, -0.42]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube004_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table005.geometry}
          material={materials["Material.005"]}
          position={[-0.2, 4.56, -0.28]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table010.geometry}
          material={materials["Material.005"]}
          position={[-0.2, 4.56, -0.14]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table015.geometry}
          material={materials["Material.005"]}
          position={[-0.2, 4.56, 0.02]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube016.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube019_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table020.geometry}
          material={materials["Material.005"]}
          position={[-0.2, 4.56, 0.16]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube021.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube023.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube024_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table025.geometry}
          material={materials["Material.005"]}
          position={[-0.2, 4.56, 0.3]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube026.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube027.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube028.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table030.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, -0.42]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube033.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube034_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table035.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, -0.28]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube036.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube037.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube038.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube039_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table040.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, -0.14]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube041.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube042.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube043.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube044_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table045.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, 0.02]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube046.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube047.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube048.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table050.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, 0.16]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube051.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube052.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube053.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table055.geometry}
          material={materials["Material.005"]}
          position={[-0.47, 4.56, 0.3]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube056.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube057.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube058.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube059_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table060.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, -0.42]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube061.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube062.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube063.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube064_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table065.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, -0.28]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube066.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube067.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube068.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube069_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table070.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, -0.14]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube071.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube072.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube073.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube074_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table075.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, 0.02]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube076.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube077.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube078.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube079_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table080.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, 0.16]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube081.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube082.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube083.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube084_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.Pantry_Table085.geometry}
          material={materials["Material.005"]}
          position={[-0.73, 4.56, 0.3]}
          scale={[0, 5, 0]}
        >
          <mesh
            geometry={nodes.Cube086.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube087.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, 0.13]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube088.geometry}
            material={materials["Material.006"]}
            position={[-41.72, 0.34, -17.63]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
          <mesh
            geometry={nodes.Cube089_1.geometry}
            material={materials["Material.006"]}
            position={[-14.68, 0.34, -17.69]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[10, 0.1, 7.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.right_wall.geometry}
          material={materials.wall_Material}
          position={[-1, 23.83, 0]}
          rotation={[0, 0, -1.57]}
          scale={[25, 0.01, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/office_1.glb");
