/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 .\office_2.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/office_2.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[79.35, 21.6, 30.49]} scale={[4, 4, 1]}>
        {/* <mesh
          geometry={nodes.Cube146.geometry}
          material={materials.Whole_Stand}
        /> */}
        {/* <mesh
          geometry={nodes.Cube146_1.geometry}
          material={materials.Flower_Pot_Block}
        /> */}
        {/* <group position={[0.75, -0.5, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder032.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder032_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf001.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf002.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf003.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf004.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf005.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf006.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
        </group> */}
        {/* <group position={[0, -0.5, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder033.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder033_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf007.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf008.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf009.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf010.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf011.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf012.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf013.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[-0.74, -0.5, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder034.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder034_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf014.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf015.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf016.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf017.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf018.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf019.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf020.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[-0.37, -0.12, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder035.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder035_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf021.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf022.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf023.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf024.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf025.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf026.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf027.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[0.38, -0.12, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder036.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder036_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf028.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf029.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf030.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf031.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf032.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf033.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf034.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[0.75, 0.25, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder040.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder040_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf035.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf036.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf037.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf038.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf039.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf040.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf041.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[0, 0.25, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder041.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder041_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf042.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf043.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf044.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf045.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf046.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf047.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf048.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[-0.74, 0.25, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder042.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder042_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf049.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf050.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf051.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf052.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf053.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf054.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf055.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[-0.37, 0.63, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder043.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder043_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf056.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf057.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf058.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf059.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf060.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf061.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf062.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
        {/* <group position={[0.38, 0.63, 0]} scale={[0.06, 0.06, 0.26]}>
          <mesh
            geometry={nodes.Cylinder044.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder044_1.geometry}
            material={materials.Sand}
          />
          <mesh
            geometry={nodes.Leaf063.geometry}
            material={materials["Material.007"]}
            position={[-0.14, 1.78, -1.78]}
            rotation={[0.43, 0, 0]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf064.geometry}
            material={materials["Material.007"]}
            position={[1.13, 1.27, -0.03]}
            rotation={[Math.PI / 2, -1.14, Math.PI / 2]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf065.geometry}
            material={materials["Material.007"]}
            position={[0.12, 1.23, 0.96]}
            rotation={[2.71, 0, Math.PI]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf066.geometry}
            material={materials["Material.007"]}
            position={[0.25, 1.15, -1.12]}
            scale={[0.12, 1.82, 0.84]}
          />
          <mesh
            geometry={nodes.Leaf067.geometry}
            material={materials["Material.007"]}
            position={[1.52, 1.86, 0.09]}
            rotation={[1.72, -1.13, 1.74]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf068.geometry}
            material={materials["Material.007"]}
            position={[-0.51, 1.67, 1.66]}
            rotation={[2.7, 0.18, -3.06]}
            scale={[0.29, 2, 2]}
          />
          <mesh
            geometry={nodes.Leaf069.geometry}
            material={materials["Material.007"]}
            position={[-1.88, 1.81, -0.18]}
            rotation={[1.42, 1.13, -1.41]}
            scale={[0.29, 2, 2]}
          />
        </group> */}
      </group>
      <group position={[85.75, 64.17, -40.89]} scale={[4.64, 2, 1]}>
        {/* <mesh geometry={nodes.Cube.geometry} material={materials.Material} /> */}
        {/* <mesh geometry={nodes.Cube_1.geometry} material={materials.Face} /> */}
        {/* <mesh geometry={nodes.Cube_2.geometry} material={materials.Basement} /> */}
        {/* <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials.Coffee_Bay_Door}
        /> */}
        {/* <mesh
          geometry={nodes.Coffee001.geometry}
          material={materials.Coffee_Machine_Color}
          position={[0.76, -0.05, -0.14]}
          scale={[0.12, 0.29, 0.57]}
        >
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Coffee_Cup}
            position={[0.4, 0.17, -0.51]}
            scale={[0.09, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials.Coffee_Cup}
            position={[-0.31, 0.17, -0.51]}
            scale={[0.08, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Text.geometry}
            material={materials["Material.001"]}
            position={[0.73, 0.57, -1.01]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.52}
          />
        </mesh>
        <mesh
          geometry={nodes.Coffee002.geometry}
          material={materials.Coffee_Machine_Color}
          position={[0.4, -0.05, -0.14]}
          scale={[0.12, 0.29, 0.57]}
        >
          <mesh
            geometry={nodes.Cylinder012.geometry}
            material={materials.Coffee_Cup}
            position={[0.4, 0.17, -0.51]}
            scale={[0.09, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Cylinder016_1.geometry}
            material={materials.Coffee_Cup}
            position={[-0.31, 0.17, -0.51]}
            scale={[0.08, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Text005.geometry}
            material={materials["Material.001"]}
            position={[0.73, 0.57, -1.01]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.52}
          />
        </mesh>
        <mesh
          geometry={nodes.Coffee003.geometry}
          material={materials.Coffee_Machine_Color}
          position={[0.01, -0.05, -0.14]}
          scale={[0.12, 0.29, 0.57]}
        >
          <mesh
            geometry={nodes.Cylinder017_1.geometry}
            material={materials.Coffee_Cup}
            position={[0.4, 0.17, -0.51]}
            scale={[0.09, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Cylinder018_1.geometry}
            material={materials.Coffee_Cup}
            position={[-0.31, 0.17, -0.51]}
            scale={[0.08, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Text006.geometry}
            material={materials["Material.001"]}
            position={[0.73, 0.57, -1.01]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.52}
          />
        </mesh>
        <mesh
          geometry={nodes.Coffee004.geometry}
          material={materials.Coffee_Machine_Color}
          position={[-0.36, -0.05, -0.14]}
          scale={[0.12, 0.29, 0.57]}
        >
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials.Coffee_Cup}
            position={[0.4, 0.17, -0.51]}
            scale={[0.09, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Cylinder020.geometry}
            material={materials.Coffee_Cup}
            position={[-0.31, 0.17, -0.51]}
            scale={[0.08, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Text007.geometry}
            material={materials["Material.001"]}
            position={[0.73, 0.57, -1.01]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.52}
          />
        </mesh>
        <mesh
          geometry={nodes.Coffee005.geometry}
          material={materials.Coffee_Machine_Color}
          position={[-0.72, -0.05, -0.14]}
          scale={[0.12, 0.29, 0.57]}
        >
          <mesh
            geometry={nodes.Cylinder021.geometry}
            material={materials.Coffee_Cup}
            position={[0.4, 0.17, -0.51]}
            scale={[0.09, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Cylinder022.geometry}
            material={materials.Coffee_Cup}
            position={[-0.31, 0.17, -0.51]}
            scale={[0.08, 0.18, 0.18]}
          />
          <mesh
            geometry={nodes.Text008.geometry}
            material={materials["Material.001"]}
            position={[0.73, 0.57, -1.01]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.52}
          />
        </mesh> */}
        {/* <mesh
          geometry={nodes.Coffee_Door_Oepner.geometry}
          material={materials.Door_Opener}
          position={[0.69, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Coffee_Door_Oepner002.geometry}
          material={materials.Door_Opener}
          position={[0.38, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Coffee_Door_Oepner003.geometry}
          material={materials.Door_Opener}
          position={[0.06, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Coffee_Door_Oepner004.geometry}
          material={materials.Door_Opener}
          position={[-0.27, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Coffee_Door_Oepner005.geometry}
          material={materials.Door_Opener}
          position={[-0.59, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Coffee_Door_Oepner006.geometry}
          material={materials.Door_Opener}
          position={[-0.91, -0.54, -0.97]}
          rotation={[-Math.PI / 2, 1.57, 0]}
          scale={[0.04, 0.08, 0.02]}
        />
        <mesh
          geometry={nodes.Text004.geometry}
          material={materials["Material.002"]}
          position={[-0.03, 0.56, -1.01]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.22, 1, 0.5]}
        /> */}
      </group>
      {/* <mesh
        geometry={nodes.Pantry_Chair_Original.geometry}
        material={materials.Seat_Color}
        position={[19.7, 41.88, 20.47]}
        scale={[2, 0.3, 2]}
      >
        <mesh
          geometry={nodes.Chair_Seat.geometry}
          material={materials["Material.009"]}
          position={[0, 6.04, -0.97]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.15, 6.67]}
        />
        <mesh
          geometry={nodes.Chair_Stand003.geometry}
          material={materials.Chair_Stand}
          position={[-0.61, -4.2, 0.63]}
          scale={[0.05, 3.33, 0.05]}
        />
        <mesh
          geometry={nodes.Chair_Stand004.geometry}
          material={materials.Chair_Stand}
          position={[-0.65, -4.16, -0.65]}
          scale={[0.05, 3.33, 0.05]}
        />
        <mesh
          geometry={nodes.Chair_Stand005.geometry}
          material={materials.Chair_Stand}
          position={[0.71, -4.2, 0.63]}
          scale={[0.05, 3.33, 0.05]}
        />
        <mesh
          geometry={nodes.Chair_Stand006.geometry}
          material={materials.Chair_Stand}
          position={[0.67, -4.16, -0.65]}
          scale={[0.05, 3.33, 0.05]}
        />
      </mesh> */}
      {/* <mesh
        geometry={nodes.Table_Original.geometry}
        material={materials.Table_Top}
        position={[64.65, 39.38, 31.68]}
        scale={[11.63, 0.44, 5]}
      >
        <mesh
          geometry={nodes.Table_Stand004.geometry}
          material={materials.Table_Stand}
          position={[0.91, -4.78, -0.77]}
          scale={[0.02, 4.52, 0.04]}
        />
        <mesh
          geometry={nodes.Table_Stand005.geometry}
          material={materials.Table_Stand}
          position={[0.91, -4.78, 0.79]}
          scale={[0.02, 4.52, 0.04]}
        />
        <mesh
          geometry={nodes.Table_Stand006.geometry}
          material={materials.Table_Stand}
          position={[-0.89, -4.78, -0.78]}
          scale={[0.02, 4.52, 0.04]}
        />
        <mesh
          geometry={nodes.Table_Stand007.geometry}
          material={materials.Table_Stand}
          position={[-0.89, -4.78, 0.78]}
          scale={[0.02, 4.52, 0.04]}
        />
      </mesh> */}
      {/* <mesh
        geometry={nodes.Office_Chair_Original.geometry}
        material={materials.Chair_Seat}
        position={[-53.57, 57.05, 40.43]}
        scale={[2, 0.3, 2]}
      >
        <mesh
          geometry={nodes.Chair_Hand001.geometry}
          material={materials.Chiar_Handle}
          position={[-1, 4.05, -0.41]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.63, 0.28, 0.09]}
        />
        <mesh
          geometry={nodes.Chair_Seat001.geometry}
          material={materials.Chair_Cover}
          position={[0, 6.04, -0.97]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.15, 6.67]}
        />
        <mesh
          geometry={nodes.Chair_Stand001.geometry}
          material={nodes.Chair_Stand001.material}
          position={[-0.03, -4.29, -0.06]}
          scale={[0.05, 3.33, 0.05]}
        >
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={nodes.Cube001_1.material}
            position={[-0.27, -1, 0]}
            rotation={[0, Math.PI / 4, 0]}
            scale={[20.01, 0.08, 2.22]}
          >
            <mesh
              geometry={nodes.Wheel_Outer004.geometry}
              material={materials.Black_Wheel}
              position={[-0.96, -3.07, -0.04]}
              rotation={[1.39, -1.24, -0.2]}
              scale={[2.22, 1.05, 0.14]}
            >
              <group position={[-0.16, 0, 0.01]} scale={0.74}>
                <mesh
                  geometry={nodes.Cylinder019_1.geometry}
                  material={materials.Black_Wheel}
                />
                <mesh
                  geometry={nodes.Cylinder019_2.geometry}
                  material={materials.Base_Color}
                />
              </group>
            </mesh>
            <mesh
              geometry={nodes.Wheel_Outer007.geometry}
              material={materials.Black_Wheel}
              position={[0.87, -3.1, 0.3]}
              rotation={[1.39, -1.24, -0.2]}
              scale={[2.22, 1.05, 0.14]}
            >
              <group position={[-0.16, 0, 0.01]} scale={0.74}>
                <mesh
                  geometry={nodes.Cylinder025.geometry}
                  material={materials.Black_Wheel}
                />
                <mesh
                  geometry={nodes.Cylinder025_1.geometry}
                  material={materials.Base_Color}
                />
              </group>
            </mesh>
          </mesh>
          <mesh
            geometry={nodes.Cube002_1.geometry}
            material={nodes.Cube002_1.material}
            position={[-0.27, -1, 0]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            scale={[20.01, 0.08, 2.7]}
          >
            <mesh
              geometry={nodes.Wheel_Outer005.geometry}
              material={materials.Black_Wheel}
              position={[-0.89, -3.22, -0.09]}
              rotation={[1.39, -1.24, -0.2]}
              scale={[2.22, 1.05, 0.14]}
            >
              <group position={[-0.16, 0, 0.01]} scale={0.74}>
                <mesh
                  geometry={nodes.Cylinder021_1.geometry}
                  material={materials.Black_Wheel}
                />
                <mesh
                  geometry={nodes.Cylinder021_2.geometry}
                  material={materials.Base_Color}
                />
              </group>
            </mesh>
            <mesh
              geometry={nodes.Wheel_Outer006.geometry}
              material={materials.Black_Wheel}
              position={[0.89, -2.85, -0.03]}
              rotation={[1.46, -1.21, -0.16]}
              scale={[2.21, 0.87, 0.12]}
            >
              <group position={[-0.16, 0, 0.01]} scale={0.74}>
                <mesh
                  geometry={nodes.Cylinder023.geometry}
                  material={materials.Black_Wheel}
                />
                <mesh
                  geometry={nodes.Cylinder023_1.geometry}
                  material={materials.Base_Color}
                />
              </group>
            </mesh>
          </mesh>
        </mesh>
        <mesh
          geometry={nodes.Chair_Stand002.geometry}
          material={materials.Chiar_Handle}
          position={[0.99, 4.05, -0.41]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.63, 0.28, 0.09]}
        />
      </mesh> */}
      <group position={[-60, 0, 80]} scale={[60, 0.2, 80]}>
        <mesh
          geometry={nodes.Cube028.geometry}
          material={materials.Table_Stand}
        />
        <mesh
          geometry={nodes.Cube028_1.geometry}
          material={materials.Table_Top}
        />
        <mesh
          geometry={nodes.Cube028_2.geometry}
          material={materials.Chair_Seat}
        />
        <mesh
          geometry={nodes.Cube028_3.geometry}
          material={materials.Chair_Cover}
        />
        <mesh
          geometry={nodes.Cube028_4.geometry}
          material={materials.Chiar_Handle}
        />
        <mesh
          geometry={nodes.Cube028_5.geometry}
          material={materials.Black_Wheel}
        />
        <mesh
          geometry={nodes.Cube028_6.geometry}
          material={materials.Base_Color}
        />
        <mesh
          geometry={nodes.Cube028_7.geometry}
          material={materials.Monitor_Color}
        />
        <mesh
          geometry={nodes.Cube028_8.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube028_9.geometry}
          material={materials.Keyboard_Keys_Color}
        />
        <mesh
          geometry={nodes.Cube028_10.geometry}
          material={materials.Mouse_Whole_Color}
        />
        <mesh
          geometry={nodes.Cube028_11.geometry}
          material={materials.Mouse_Click_Color}
        />
        <mesh
          geometry={nodes.Cube028_12.geometry}
          material={materials.Floor_Outline_Color}
        />
        <mesh
          geometry={nodes.Cube028_13.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Cube028_14.geometry} material={materials.Face} />
        <mesh
          geometry={nodes.Cube028_15.geometry}
          material={materials.Basement}
        />
        <mesh
          geometry={nodes.Cube028_16.geometry}
          material={materials.Coffee_Bay_Door}
        />
        <mesh
          geometry={nodes.Cube028_17.geometry}
          material={materials.Coffee_Machine_Color}
        />
        <mesh
          geometry={nodes.Cube028_18.geometry}
          material={materials.Coffee_Cup}
        />
        <mesh
          geometry={nodes.Cube028_19.geometry}
          material={materials.Door_Opener}
        />
        <mesh
          geometry={nodes.Cube028_20.geometry}
          material={materials.Seat_Color}
        />
        <mesh
          geometry={nodes.Cube028_21.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Cube028_22.geometry}
          material={materials.Chair_Stand}
        />
        <mesh
          geometry={nodes.Cube028_23.geometry}
          material={materials["Whole.001"]}
        />
        <mesh
          geometry={nodes.Cube028_24.geometry}
          material={materials.Laptop_Stand}
        />
        <mesh geometry={nodes.Cube028_25.geometry} material={materials.Whole} />
        <mesh geometry={nodes.Cube028_26.geometry} material={materials.Door} />
        <mesh
          geometry={nodes.Cube028_27.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Cube028_28.geometry}
          material={materials.Window_Outliner}
        />
        <mesh geometry={nodes.Cube028_29.geometry} material={materials.Glass} />
        <mesh
          geometry={nodes.Cube028_30.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube028_31.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cube028_32.geometry}
          material={materials.Desk_Color}
        />
        <mesh
          geometry={nodes.Cube028_33.geometry}
          material={materials.Border_Color}
        />
        <mesh
          geometry={nodes.Cube028_34.geometry}
          material={materials.Whole_Stand}
        />
        <mesh
          geometry={nodes.Cube028_35.geometry}
          material={materials.Flower_Pot_Block}
        />
        <mesh
          geometry={nodes.Cube028_36.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube028_37.geometry}
          material={materials["Material.008"]}
        />
        <mesh geometry={nodes.Cube028_38.geometry} material={materials.Sand} />
        {/* <mesh
          geometry={nodes.Ceiling.geometry}
          material={nodes.Ceiling.material}
          position={[0, 198.07, 0]}
        /> */}
        {/* <mesh
          geometry={nodes.Left_Wall.geometry}
          material={nodes.Left_Wall.material}
          position={[-1, 99, 0]}
          rotation={[0, 0, -1.57]}
          scale={[100, 0, 1]}
        /> */}
        {/* <mesh
          geometry={nodes.Right_Wall.geometry}
          material={nodes.Right_Wall.material}
          position={[0.99, 99, 0]}
          rotation={[0, 0, -1.57]}
          scale={[100, 0, 1]}
        /> */}
      </group>
      {/* <group position={[17.43, 5.22, -97.81]} scale={[0.2, 1, 2]}>
        <mesh
          geometry={nodes.Cube032.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube032_1.geometry}
          material={materials["Material.004"]}
        />
      </group> */}
      {/* <mesh
        geometry={nodes.Office_Monitor_Original.geometry}
        material={materials.Monitor_Color}
        position={[12.36, 27.93, -10.19]}
        scale={[0.1, 1, 2]}
      >
        <mesh
          geometry={nodes.Keyboard.geometry}
          material={materials["Material.005"]}
          position={[-25.89, -1.6, -0.34]}
          rotation={[Math.PI, 0, 2.69]}
          scale={[6.85, 0.08, 0.82]}
        >
          <mesh
            geometry={nodes.Cube006.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.78, 1.12, 0.08]}
            scale={[0.1, 0.1, 0.33]}
          />
          <mesh
            geometry={nodes.Cube007.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube011.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube012.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube013.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.84]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.1, -0.1, -0.12]}
          />
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, 0.84]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.1, -0.1, -0.12]}
          />
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, 0.05]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, -0.08]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube017.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, -0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube018.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.84, 1.12, -0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube033_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.56, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube034.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.56, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube035.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube036_1.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube037.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube038.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube039.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube040.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube041.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, 0.05]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube042.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, -0.08]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube043.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, -0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube044.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, -0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube047.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube048.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.29, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube049.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube050.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube051.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube052.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube053.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube054.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube055.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, 0.05]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube056.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, -0.08]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube057.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, -0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube058.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, -0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube061.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube062.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[-0.02, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube064.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.84]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.1, -0.1, -0.12]}
          />
          <mesh
            geometry={nodes.Cube065.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube066.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube067.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube068.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube069.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, 0.05]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube070.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, -0.08]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube071.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, -0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube072.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, -0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube075.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube076.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.24, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube079.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube080.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube081.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube082.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube083.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, 0.05]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube084.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.08]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube085.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.22]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube086.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.36]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube087.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube088.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube089.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube090.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.51, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube093.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, 0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube094.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, 0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube101.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, -0.5]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube102.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, -0.63]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube103.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, -0.77]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Cube104.geometry}
            material={materials.Keyboard_Keys_Color}
            position={[0.76, 1.12, -0.91]}
            scale={[0.1, 0.1, 0.05]}
          />
          <mesh
            geometry={nodes.Keyboard_Stand.geometry}
            material={nodes.Keyboard_Stand.material}
            position={[-0.8, -1.41, -0.83]}
            rotation={[0, 0, 0.57]}
            scale={[0.29, 0.19, 0]}
          />
          <mesh
            geometry={nodes.Keyboard_Stand001.geometry}
            material={nodes.Keyboard_Stand001.material}
            position={[-0.8, -1.41, 0.81]}
            rotation={[0, 0, 0.57]}
            scale={[0.29, 0.19, 0]}
          />
        </mesh>
        <mesh
          geometry={nodes.Monitor_Stand.geometry}
          material={materials.Monitor_Color}
          position={[1.53, -1.05, 0]}
          scale={[0.54, 0.7, 0.03]}
        >
          <mesh
            geometry={nodes.Cube003.geometry}
            material={materials.Monitor_Color}
            position={[-4.82, -0.96, 3.71]}
            rotation={[-Math.PI, 0.78, -Math.PI]}
            scale={[1.42, 0.07, 6.64]}
          />
          <mesh
            geometry={nodes.Cube004.geometry}
            material={materials.Monitor_Color}
            position={[-4.82, -0.95, -3.85]}
            rotation={[0, 0.78, 0]}
            scale={[1.42, 0.07, 6.64]}
          />
        </mesh>
        <group
          position={[-25.55, -1.76, 0.97]}
          rotation={[0, -1.57, 0]}
          scale={[0.1, 0.2, 4]}
        >
          <mesh
            geometry={nodes.Cube142.geometry}
            material={materials.Mouse_Whole_Color}
          />
          <mesh
            geometry={nodes.Cube142_1.geometry}
            material={materials.Mouse_Click_Color}
          />
          <mesh
            geometry={nodes.Cylinder009.geometry}
            material={materials.Mouse_Click_Color}
            position={[0, 1.01, -0.57]}
            rotation={[-Math.PI, 0, -Math.PI / 2]}
            scale={[0.11, 0.1, 0.16]}
          />
        </group>
      </mesh> */}
      {/* <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.002"]}
        position={[-1.52, 3.11, -1.01]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      /> */}
      {/* <group rotation={[0, Math.PI / 2, 0]} scale={[2.36, 2.36, 11.82]}>
        <mesh
          geometry={nodes.Cube198.geometry}
          material={materials["Whole.001"]}
        />
        <mesh
          geometry={nodes.Cube198_1.geometry}
          material={materials.Laptop_Stand}
        />
      </group> */}
      {/* <group position={[64.21, 15.55, -102.63]} scale={[14.74, 0.44, 5.89]}>
        <mesh
          geometry={nodes.Cube224.geometry}
          material={materials.Table_Top}
        />
        <mesh
          geometry={nodes.Cube224_1.geometry}
          material={materials.Table_Stand}
        />
      </group> */}
      {/* <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.010"]}
        position={[44.29, 39.24, -94.65]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.22, 1.36, 1.36]}
      /> */}
      {/* <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.010"]}
        position={[44.29, 39.24, -94.65]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.22, 1.36, 1.36]}
      /> */}
      {/* <group position={[-91.91, 22.66, -67.04]} scale={[4.11, 8.05, 0.4]}>
        <mesh geometry={nodes.Cube239.geometry} material={materials.Whole} />
        <mesh geometry={nodes.Cube239_1.geometry} material={materials.Door} />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["Material.010"]}
          position={[0.71, 0, 0.05]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.02, 2.73, 0.27]}
        />
      </group> */}
    </group>
  );
}

useGLTF.preload("/office_2.glb");
