/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/floor_with_animation.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.floor}
        position={[0, 0.1, 0]}
        scale={[6, 0.1, 6]}
      >
        <mesh
          geometry={nodes.table_with_chairs.geometry}
          material={materials["Material.002"]}
          position={[0.93, 4.51, 0.77]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube004.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube005.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs001.geometry}
          material={materials["Material.002"]}
          position={[0.93, 4.51, 0.13]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube002.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube006.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube007.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs002.geometry}
          material={materials["Material.002"]}
          position={[0.93, 4.51, -0.54]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube009.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube010.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube011.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube012.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs003.geometry}
          material={materials["Material.002"]}
          position={[0.25, 4.51, 0.77]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube015.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube016.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs004.geometry}
          material={materials["Material.002"]}
          position={[0.25, 4.51, 0.13]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube017.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube019.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube020.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs005.geometry}
          material={materials["Material.002"]}
          position={[0.25, 4.51, -0.54]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube021.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube024.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs006.geometry}
          material={materials["Material.002"]}
          position={[-0.44, 4.51, 0.77]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube025.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube026.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube027.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube028_1.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs007.geometry}
          material={materials["Material.002"]}
          position={[-0.44, 4.51, 0.13]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube029.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube030.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
        <mesh
          geometry={nodes.table_with_chairs008.geometry}
          material={materials["Material.002"]}
          position={[-0.44, 4.51, -0.54]}
          scale={[0.01, 4.19, 0.02]}
        >
          <mesh
            geometry={nodes.Cube033_1.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube034.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, 2.01]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube035.geometry}
            material={materials["Material.001"]}
            position={[-14.42, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
          <mesh
            geometry={nodes.Cube036.geometry}
            material={materials["Material.001"]}
            position={[-39.77, 0.4, -18.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[8.76, 0.12, 5.15]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("/floor_with_animation.glb");
